### ISSUE TITLE
Transition checklist

### ISSUE THREAD

**Issue by shawnbot** [RTICWDT/college-scorecard#1535]
Front end:
- [x] **18F**: manually remove Federalist webhooks
- [x] **18F**: Transfer the repo to RTI
- [x] **RTI**: Rename the repo to `college-scorecard` (or similar, e.g. `ed-college-scorecard`)
- [x] **RTI & 18F**: Add the new repo to Federalist
- [x] **RTI**: add the new repo to Circle CI
- [x] **RTI**: push changes to a new branch to test Federalist previews
- [x] **RTI**: Update Circle CI environment variables to use RTI Sauce Labs credentials
- **All**: Run through the [release process](https://github.com/18F/college-choice/wiki/Workflow#workflow):
  - [x] Make a non-breaking change in a new branch
  - [x] File a PR against `dev` to test the CI setup (repeat as necessary)
  - [x] File a PR to merge `dev` to `staging` and ensure that tests pass
  - [x] File a PR to merge `staging` to `master`; watch tests pass
  - [x] Update the Federalist configuration with the custom domain `https://collegescorecard.ed.gov`
  - [x] Merge the PR to publish the site! 🎉 
- [x] **18F**: Update the CDN origin to map to the new site's S3 origin path
- [x] **RTI**: Sign up for new API keys on api.data.gov
- [x] **18F**: Grant RTI users admin access to the API configuration
- [x] **RTI**: update [Federalist config](https://federalist.18f.gov/#site/292/settings) to use RTI API keys
- [x] **RTI**: Update SSL certificates (~~TODO: ask @konklone what's needed here~~)
- [x] **RTI**: Update the Federalist custom config to use the new dev API `baseurl` and `key`
- [x] Anyone: Remove the old site from Federalist

Data:
- [x] Transfer `college-choice-data` to RTI
- [x] Update links in other repos?

API:
- [x] **Anyone**: Update api.data.gov origin URLs to point to the new/alternate apps.cloud.gov hostnames
- [x] **18F & RTI**: look at service proxy domain names
- [x] **18F & RTI**: Get RTI College Scorecard New Relic sub-account set up
  - [x] **18F & RTI**: Walk RTI folks through existing sub-account, alerting, synthetics setup
  - [x] **RTI**: Restage ccapi instances with the new New Relic sub-account license key

Domain: 
- [x] **RTI**: Work with Ed to transfer domain from 18F 

/cc @abisker @yozlet @kynetiv @jeremiak @wslack

**Comment by konklone** [comment]
Just to be clear, the infrastructure/cloud.gov/federalist team should be able to handle the TLS certificates. Unsubscribing, but ping me in Slack if there's anything special I can help with.

**Comment by shawnbot** [comment]
Transition update: the repo is transferred and renamed, previews are building on Federalist, and RTI has the site added to Circle CI with new Sauce Labs credentials. RTI has set the default API `baseurl` and `key` to the production API so that we can test Federalist previews with a working API (because the dev API is down right now).

**Comment by shawnbot** [comment]
Update: the site is transferred on Federalist, a new version has been released, all branches are building successfully, and tests are passing! 🎉 

You should see `v1.7.8` at the bottom of [collegescorecard.ed.gov](https://collegescorecard.ed.gov/).

**Comment by abisker** [comment]
@yozlet Under which of the three headings above do you want these tasks to fall, data?

1. Task: Understand and repoint the downloads bucket
2. Task: Sort out DNS for collegescorecard.ed.gov … ED has delegated responsibilities; Do we need to be hosting that so we can auto-point? Does federalist NEED control of this? 
3. Task: New Relic Updated/Troubleshooting

**Comment by yozlet** [comment]
@abisker I suspect 1. falls under Front-End, because that's what uses it. 

Same with 2 - can't remember what the Federalist dependencies are there, maybe @wslack @jeremiak can help? And if there _aren't_ any Federalist dependencies, and `collegescorecard.ed.gov` can stay pointed/CNAMEd at one particular address, perhaps we can just tell ED to do that pointing themselves, instead of delegating to us.

Task 3 is underway, part of the API work. The task list is missing the words "New Relic" in the right place, so let me fix that now...

**Comment by yozlet** [comment]
... okay, I can't edit it. @shawnbot, can you make it say "Get RTI College Scorecard **New Relic** sub-account set up"? Thanks!

(And actually, it's not a sub-account for the moment. This is their first New Relic account, so they're keeping it at the top level)

**Comment by kynetiv** [comment]
@abisker, I also wanted to chime in about 2.  Depending on who manages the `collegescorecard.ed.gov` domain, we need to address how the SSL is updated and by whom. Right now I believe the domain is managed in 18F's Amazon Route 53 for use by CloudFront. If that continues to be the case It would make sense to have the cert provided by 18F's Amazon Cert Manager. 

Also not sure if we need to discuss transfer of the Open Data Maker repo here or if RTI is going move and maintain this project as a fork.

**Comment by kynetiv** [comment]
Thanks @yozlet , i've updated the list for the New Relic bullet. We're planning to update this account soon (during non-peak hours).

/cc @shawnbot

**Comment by djharrity** [comment]
The Smart Search function of Safari browser on iOS devices displays as Research Triangle Institute and not CollegeScorecard.ed.gov or College Scorecard.

**Comment by brownpl** [comment]
With a recent Federalist migration, the iOS Smart Search is now displaying the URL as expected. 

Closing this issue as we are now completely transitioned! Thanks again for all the great support you all have provided us during this transition.

**Comment by wslack** [comment]
🎉
